"""Turn the leaderboard into a succinct, blog/paper-ready FINDINGS.md + plots."""
from __future__ import annotations
import os, csv

RUNS_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "runs")


def _load(path):
    with open(path) as f:
        return [{k: _num(v) for k, v in row.items()} for row in csv.DictReader(f)]


def _num(v):
    try:
        return float(v) if "." in str(v) or str(v).isdigit() else v
    except Exception:
        return v


def _pareto(board):
    """F1-vs-latency Pareto frontier (maximize F1, minimize latency)."""
    pts = sorted(board, key=lambda r: (float(r["latency"]), -float(r["f1"])))
    front, best_f1 = [], -1.0
    for r in pts:
        if float(r["f1"]) > best_f1:
            front.append(r); best_f1 = float(r["f1"])
    return front


def plots(board, out_dir):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as e:  # noqa: BLE001
        return [f"(plots skipped: {e})"]
    os.makedirs(out_dir, exist_ok=True)
    made = []
    # F1 vs latency scatter + frontier
    fig, ax = plt.subplots(figsize=(7, 5))
    xs = [float(r["latency"]) for r in board]; ys = [float(r["f1"]) for r in board]
    ax.scatter(xs, ys, alpha=0.6)
    fr = _pareto(board)
    ax.plot([float(r["latency"]) for r in fr], [float(r["f1"]) for r in fr], "r-o", label="Pareto frontier")
    ax.set_xlabel("avg latency / question (s)"); ax.set_ylabel("F1")
    ax.set_title("ARES: quality vs cost across agent configs"); ax.legend()
    p = os.path.join(out_dir, "pareto.png"); fig.tight_layout(); fig.savefig(p, dpi=130); plt.close(fig); made.append(p)
    # top configs bar
    top = sorted(board, key=lambda r: float(r["f1"]), reverse=True)[:10]
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.barh([r["name"] for r in top][::-1], [float(r["f1"]) for r in top][::-1])
    ax.set_xlabel("F1"); ax.set_title("ARES: top configs by F1")
    p = os.path.join(out_dir, "top_configs.png"); fig.tight_layout(); fig.savefig(p, dpi=130); plt.close(fig); made.append(p)
    return made


def generate(out_dir=RUNS_DIR):
    lb = os.path.join(out_dir, "leaderboard.csv")
    if not os.path.exists(lb):
        return "(no leaderboard yet)"
    board = _load(lb)
    if not board:
        return "(empty leaderboard)"
    board.sort(key=lambda r: (float(r["f1"]), float(r["em"])), reverse=True)
    best = board[0]
    baseline = next((r for r in board if r["name"] == "baseline"), None)
    made = plots(board, os.path.join(out_dir, "plots"))
    fr = _pareto(board)

    def row(r):
        return (f"| {r['name']} | {float(r['f1']):.3f} | {float(r['em']):.3f} | "
                f"{float(r['recall']):.3f} | {float(r['grounding']):.3f} | {float(r['latency']):.2f} |")

    lift = ""
    if baseline and float(baseline["f1"]) > 0:
        d = (float(best["f1"]) - float(baseline["f1"])) / float(baseline["f1"]) * 100
        lift = f" (**{d:+.1f}%** vs baseline F1 {float(baseline['f1']):.3f})"

    md = [
        "# ARES — Findings",
        "",
        f"Searched **{len(board)} agentic-RAG configurations** on a HotpotQA-style multi-hop QA set, "
        "fully local on Apple Silicon (MPS). Each config varies retrieval depth, dense/BM25 hybrid weight, "
        "prompt style, query decomposition, and self-reflection.",
        "",
        "## Best configuration",
        f"**{best['name']}** — F1 **{float(best['f1']):.3f}**{lift}, EM {float(best['em']):.3f}, "
        f"retrieval recall {float(best['recall']):.3f}, groundedness {float(best['grounding']):.3f}, "
        f"avg latency {float(best['latency']):.2f}s/question.",
        "",
        f"`retrieval_k={best['retrieval_k']}  hybrid_alpha={best['hybrid_alpha']}  "
        f"prompt={best['prompt_variant']}  decompose={best['decompose']}  reflect={best['reflect']}`",
        "",
        "## Top 10 configs",
        "| config | F1 | EM | retrieval recall | groundedness | latency (s) |",
        "|---|---|---|---|---|---|",
        *[row(r) for r in board[:10]],
        "",
        "## Quality vs cost (Pareto frontier)",
        "These configs are not dominated — each is the cheapest way to reach its F1:",
        "",
        *[f"- **{r['name']}**: F1 {float(r['f1']):.3f} @ {float(r['latency']):.2f}s" for r in fr],
        "",
        "## Plots",
        *[f"![{os.path.basename(p)}](plots/{os.path.basename(p)})" for p in made if p.endswith(".png")],
        "",
        "## Takeaways",
        _takeaways(board, baseline, best),
        "",
        "_Generated by ARES (Agentic RAG Evaluation Suite)._",
    ]
    out = "\n".join(md)
    with open(os.path.join(out_dir, "FINDINGS.md"), "w") as f:
        f.write(out)
    return out


def _takeaways(board, baseline, best):
    pts = []
    by = {r["name"]: r for r in board}
    if baseline:
        for name, label in [("decompose", "Query decomposition"), ("reflect", "Self-reflection")]:
            if name in by:
                d = float(by[name]["f1"]) - float(baseline["f1"])
                verb = "helped" if d > 0.005 else ("hurt" if d < -0.005 else "was ~neutral")
                pts.append(f"- {label} {verb} ({d:+.3f} F1 vs baseline) at "
                           f"{float(by[name]['latency']):.2f}s/q ({float(by[name]['latency'])/max(float(baseline['latency']),1e-6):.1f}x baseline latency).")
    alphas = sorted([r for r in board if r["name"].startswith("alpha") or r["name"] == "baseline"],
                    key=lambda r: float(r["f1"]), reverse=True)
    if alphas:
        pts.append(f"- Best hybrid weight was around `alpha={alphas[0]['hybrid_alpha']}` "
                   "(1.0 = pure dense, 0.0 = pure BM25).")
    pts.append(f"- Winner **{best['name']}** gives the best F1; the Pareto frontier shows the cheaper "
               "configs to use under a latency budget.")
    return "\n".join(pts)
